files <- list.files(path=".", pattern=".tex")
files <- files[2:length(files)]

sink("_all.tex")
  cat("\\documentclass[12pt,a4paper]{exam}")
  cat("\n")
  cat("\n")
  cat("\\input{../../../preamblesLaTeX/preambleExam}")
  cat("\n")
  cat("\\input{../../../preamblesLaTeX/preambleTikz}")
  cat("\n")
  cat("\n")
  cat("\\printanswers")
  cat("\n")
  cat("\n")
  cat("\\qformat{\\textbf{Questão \\thequestion}\\quad \\hfill}")
  cat("\n")
  cat("\n")
  cat("\\begin{document}")
  cat("\n")
  cat("\n")
  cat("\\begin{center}")
  cat("\n")
  cat("\\fbox{\\fbox{\\parbox{16.5cm}{")
  cat("\n")
  cat("\\centering\\bigskip")
  cat("\n")
  cat("\\large\\textbf{Questões de Matemática Financeira}")
  cat("\n")
  cat("\\bigskip}}}")
  cat("\n")
  cat("\\end{center}")
  cat("\n")
  cat("\n")
  cat("\\begin{questions}")
for (i in 1:length(files)){
  cat("\n")
  cat("\\question[]")
  cat("\n")
  cat(paste0("\\textbf{\\large\\textcolor{purple}{Arquivo: \\path{",files[i],"}}}"))
  cat("\n")
  cat("\n")
  cat(paste0("\\input{",files[i],"}"))
  cat("\n")
  cat("\\newpage")
  cat("\n")
}
  cat("\n")
  cat("\\end{questions}")
  cat("\n")
  cat("\n")
  cat("\\end{document}")
sink()
