# Coloque este código no seu arquivo _quarto.yml

# --- Opções do Projeto ---
project:
  type: default

# --- Opções Globais de Execução de Código ---
# Controla como os blocos de código (Python, R, etc.) se comportam
execute:
  eval: true   # Executa o código (padrão)
  echo: true   # Mostra o código-fonte (padrão)

# --- Configurações de Formato de Saída ---
format:
  # Tudo abaixo está aninhado sob 'revealjs', pois são opções DESTE formato
  revealjs:
    # Aparência e tema
    theme: [solarized, style.css] # Aplica o tema 'solarized' e depois seu CSS customizado por cima. Perfeito!
    vertical-align: top

    # Comportamento dos slides
    slide-level: 2         # Cria um novo slide para cada título de nível 2 (##)
    slide-number: true     # Mostra o número dos slides
    incremental: true      # Permite pausas com '...' ou '.fragment'
    
    # Opções de saída do arquivo
    embed-resources: true  # Cria um único arquivo HTML autossuficiente (ótimo para compartilhar)

# --- Opções Globais de Formatação ---
# Estas opções afetam a numeração dos títulos
number-sections: false    # Numera as seções (ex: 1. Título, 1.1 Subtítulo)

# --- Filtros e Extensões ---
# Se quiser usar o 'reveal-header', descomente e coloque aqui
# filters:
#   - fontawesome
#   - reveal-header

preview:
  browser: msedge